screenshot-format=jxl
script-opts=osc-visibility=never
screenshot-directory=~/pictures/screenshots/mpv
screenshot-template="%F-[%P] (%#01n)"
osd-fractions
force-window=yes
hwdec=auto

sub-border-style=background-box
sub-back-color=0.0/0.0/0.0/0.80
sub-color=1.0/1.0/0.0/1.0
sub-font="Calibri"
sub-ass-override=no
