screenshot-format=jxl
screenshot-directory=~/pictures/screenshots/mpv
screenshot-template="%F-[%P] (%#01n)"
script-opts=osc-visibility=never
osd-fractions
force-window=yes
hwdec=auto
sub-ass-override=no
sub-back-color=0.0/0.0/0.0/0.60
sub-color=1.0/1.0/1.0/1.0
sub-shadow-color=0.0/0.0/0.0/1.0
sub-shadow-offset=2
sub-border-color=0.0/0.0/0.0/1.0
sub-border-size=3
sub-font="Rosario Bold"
sub-bold=no
sub-font-size=52
